const SUPABASE_URL = 'https://cbpdfyauboisozcxuohi.supabase.co'
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNicGRmeWF1Ym9pc296Y3h1b2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTk5NTIwODEsImV4cCI6MjAxNTUyODA4MX0.A1DXi3mrghJdLH2j87DLsbyG8aPdPQLPbO9IGpxqTO0'
const _supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY)